# Generated by Django 5.0 on 2023-12-12 14:35

import API.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivery_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('costumer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.costumer')),
            ],
        ),
        migrations.CreateModel(
            name='DataRes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to=API.models.get_datares_file_path)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('datareq', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.datareq')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('peyment', 'peyment'), ('progress', 'progress'), ('request', 'request')], max_length=10)),
                ('costumer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.costumer')),
            ],
        ),
        migrations.CreateModel(
            name='Peyment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_paid', models.BooleanField(default=False)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('costumer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.costumer')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to=API.models.get_progress_image_path)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('costumer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.costumer')),
            ],
        ),
    ]
