# Generated by Django 4.2.7 on 2023-12-12 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_rename_img_datares_url_alter_progress_costumer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='img',
            new_name='url',
        ),
    ]
