# Generated by Django 4.2.7 on 2023-12-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_posttype_remove_post_type_costumer_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teckit',
            name='title',
            field=models.CharField(default='No Title', max_length=30),
        ),
    ]
